### ISSUE TITLE
Omit specified users from cleanup

### ISSUE THREAD

**Issue by will-moore** [ome/omero-demo-cleanup#8]
Discussed with @pwalczysko:

Need to omit multiple users from the cleanup script (don't consider them for deletion).
How best to specify these users to the commnad. Either a comma-separated list of user IDs or logins:

`omero demo-cleanup --gigabytes 10 --ignore tom,dick,harry,will,101,102,103`

Or we could use some data in the server itself to specify these "safe" users. Either put them in a group that indicates they are safe from deletion, then specify the group:

`omero demo-cleanup --gigabytes 10 --ignore-group permanent-users`

But maybe we don't want that group to show up in the UIs (might confuse users and allow data to be imported into it etc).
Another alternative is to use Tags. The client UIs don't allow you to add, remove or view Tags on Experimenters, but you can link them in the CLI: (it looks like any Tag can be used to annotate any user, even if the aren't in the same Group):

`
omero obj new ExperimenterAnnotationLink child=TagAnnotation:83076 parent=Experimenter:455
`

Then ignore tagged users: NB: this command (without `-f`) could also be used for listing those users who are Tagged with "permanent-users" Tag.

`omero demo-cleanup --gigabytes 10 --ignore-tag permanent-users`

I guess a safer option might be to use Tag ID instead of Name, in case someone else creates a Tag of the same Name.

cc @joshmoore @pwalczysko

**Comment by pwalczysko** [comment]
@will-moore Thanks a lot for your help. I would actually vote for the group option. The users on demo are allocated to groups automatically and have no choice about it. The group ``permanent-users`` will not be on their display afaik. 
But happy to be overvoted here :)

**Comment by will-moore** [comment]
If they are in a`permanent-users` group, then they will be able to see it in the webclient and switch to that group, and to import data into it from Insight.
They may choose to ignore it, and it won't show up very much if it's not their default group. And I guess it doesn't break anything if they do import data into it.
So, happy to go with that option 👍

**Comment by joshmoore** [comment]
> I guess a safer option might be to use Tag ID instead of Name, in case someone else creates a Tag of the same Name.

A user won't be able to add a tag to themselves so string would also be safe. This is how the "binary_access" KV pair on ExperimenterGroup works for allowing some groups the ability to download files.

**Comment by pwalczysko** [comment]
> They may choose to ignore it, and it won't show up very much if it's not their default group.

Ah, of course, did not think that one through. The permanent users themselves have some potential to do the wrong thing.
As @joshmoore seems to lean towards the Tag solution, and considering the safety, possibly lets go for the Tags then ?

**Comment by will-moore** [comment]
Ooops - I just went ahead with Group (didn't wait to see the other comments). I don't know if @joshmoore actually prefers Tags or was just filling in details there?

But will be easy to update to Tags...
